### ISSUE TITLE
Error when loading some hair files

### ISSUE THREAD

**Issue by moth1995** [kitserver/kitserver5#9]
we have a bug on the hairs, and i could confirm its related to the kitserver on itself not the hair model/file, because i tested the hair model by inserting on 0_text and assigning the hair via edit mode to the player and worked properly, but when i assign via the map of kitserver it fails here is some proof and also the file

nedved hair was insert via ggs on the 0_text while del piero hair was insert with kitserver i haven't manage to find the error on fserv.cpp code to help with this fix, if you can fix this will help us really a lot, because sooner there'll be newer hair models made by alegor and as i tested some of them, they won't work on pes5 because of this error and i can't find a way to fix it properly, i attached the file
[D. Maradona.zip](https://github.com/kitserver/kitserver5/files/9802675/D.Maradona.zip)

![imagen](https://user-images.githubusercontent.com/36039932/196231328-acbfa7d1-3918-4b73-863c-3ad7ed6e4e08.png)

**Comment by moth1995** [comment]
i found something new, if the player is part of the starting 11 this issue happen but if the players is a sub in this error DONT happen

**Comment by juce** [comment]
marking this as fixed, after testing the latest version with @moth1995
